apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rick-morty-secrets
  namespace: rick-morty
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-store
  target:
    name: rick-morty-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: rickmorty/database/url
  - secretKey: redis-url
    remoteRef:
      key: rickmorty/redis/url
