apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rick-morty-admin-secret
  namespace: rick-morty
spec:
  encryptedData:
    admin-api-key: PLACEHOLDER_BASE64_SEALED
  template:
    metadata:
      name: rick-morty-admin-secret
      namespace: rick-morty
    type: Opaque
